# Generated by Django 4.2.1 on 2024-09-25 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('user_id', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField()),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambotuser')),
            ],
        ),
    ]
