# Generated by Django 4.2.1 on 2024-09-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegrambotuser_bot_created_botmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user_name', models.CharField(blank=True, max_length=250, null=True)),
                ('chat_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
        ),
        migrations.DeleteModel(
            name='BotMessage',
        ),
        migrations.DeleteModel(
            name='TelegramBotUser',
        ),
    ]
