# Generated by Django 4.2.1 on 2024-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
