# Generated by Django 4.2.1 on 2024-09-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_bot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
    ]
